-- =====================================================
-- Update Storage RLS Policies for Custom JWT Claims
-- =====================================================
-- This migration updates the RLS policies to use custom
-- JWT claims instead of auth.uid().
--
-- CONTEXT: Supabase requires the 'sub' claim to be a UUID,
-- but we use Stacks addresses. The solution is to:
-- 1. Use a dummy UUID for 'sub' in the JWT
-- 2. Store the real Stacks address in user_metadata.stacks_address
-- 3. Update RLS policies to check the custom claim
-- =====================================================

-- =====================================================
-- DROP EXISTING POLICIES
-- =====================================================

-- Drop avatars bucket policies
DROP POLICY IF EXISTS "Allow authenticated users to upload own avatar" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to update own avatar" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to delete own avatar" ON storage.objects;

-- Drop posts-images bucket policies
DROP POLICY IF EXISTS "Allow authenticated users to upload own post images" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to update own post images" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to delete own post images" ON storage.objects;

-- =====================================================
-- AVATARS BUCKET POLICIES (UPDATED)
-- =====================================================

-- Allow authenticated users to upload to their own folder
-- Check against custom claim: user_metadata.stacks_address
CREATE POLICY "Allow authenticated users to upload own avatar"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'avatars' AND
  (storage.foldername(name))[1] = (auth.jwt() -> 'user_metadata' ->> 'stacks_address')
);

-- Allow authenticated users to update files in their own folder
CREATE POLICY "Allow authenticated users to update own avatar"
ON storage.objects FOR UPDATE
TO authenticated
USING (
  bucket_id = 'avatars' AND
  (storage.foldername(name))[1] = (auth.jwt() -> 'user_metadata' ->> 'stacks_address')
)
WITH CHECK (
  bucket_id = 'avatars' AND
  (storage.foldername(name))[1] = (auth.jwt() -> 'user_metadata' ->> 'stacks_address')
);

-- Allow authenticated users to delete files in their own folder
CREATE POLICY "Allow authenticated users to delete own avatar"
ON storage.objects FOR DELETE
TO authenticated
USING (
  bucket_id = 'avatars' AND
  (storage.foldername(name))[1] = (auth.jwt() -> 'user_metadata' ->> 'stacks_address')
);

-- =====================================================
-- POSTS-IMAGES BUCKET POLICIES (UPDATED)
-- =====================================================

-- Allow authenticated users to upload to their own folder
-- Check against custom claim: user_metadata.stacks_address
CREATE POLICY "Allow authenticated users to upload own post images"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'posts-images' AND
  (storage.foldername(name))[1] = (auth.jwt() -> 'user_metadata' ->> 'stacks_address')
);

-- Allow authenticated users to update files in their own folder
CREATE POLICY "Allow authenticated users to update own post images"
ON storage.objects FOR UPDATE
TO authenticated
USING (
  bucket_id = 'posts-images' AND
  (storage.foldername(name))[1] = (auth.jwt() -> 'user_metadata' ->> 'stacks_address')
)
WITH CHECK (
  bucket_id = 'posts-images' AND
  (storage.foldername(name))[1] = (auth.jwt() -> 'user_metadata' ->> 'stacks_address')
);

-- Allow authenticated users to delete files in their own folder
CREATE POLICY "Allow authenticated users to delete own post images"
ON storage.objects FOR DELETE
TO authenticated
USING (
  bucket_id = 'posts-images' AND
  (storage.foldername(name))[1] = (auth.jwt() -> 'user_metadata' ->> 'stacks_address')
);

-- =====================================================
-- NOTES
-- =====================================================
-- 1. These policies check auth.jwt() -> 'user_metadata' ->> 'stacks_address'
-- 2. The JWT is generated by the get-auth-jwt Edge Function
-- 3. The 'sub' claim contains a dummy UUID (required by Supabase)
-- 4. The real Stacks address is in user_metadata.stacks_address
-- 5. The folder structure remains: {stacks_address}/{filename}
-- 6. Public read policies remain unchanged from previous migration
-- =====================================================
